export enum FORBIDDEN {
  USER_DEACTIVE = 40300,
  USER_NOT_ACTIVE,
  ACCOUNT_LOCKED,
  LOCK_ACCOUNT,
  NOT_ADMIN,
  USER_EMAIL_NOT_VERIFIED,
  WRONG_PASS,
  WRONG_EMAIL,
  ADMIN_NOT_CHANGED_DEFAULT_PASSWORD,
  EMAIL_VERIFY_FAILD,
  EMAIL_VERIFY_EXPIRE,
  INVALID_PASSWORD,
}

export enum UNAUTHORIZED {
  INVALID_TOKEN = 40100,
  REFRESH_TOKEN_INVALID,
}

export enum BAD_REQUEST {
  NOT_EXISTS = 40000,
  SAME_PREVIOUS_PASSWORD,
}

export enum NOT_ACCEPTABLE {
  INVALID_PASSWORD = 40600,
  WALLET_ADDRESS_USED,
}

export enum NOT_FOUND {
  NOT_EXISTS = 40400,
}
